[package]
name = "workout-tracker-pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4"
rppal = "0.18.0"

[dependencies.rusqlite]
version = "0.31.0"
features = ["bundled"]

[dependencies.epd-waveshare]
# TODO: Switch to git once PR for 2in7_v2 is up
path = "../epd-waveshare"
