[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono-tz = { workspace = true }
crossbeam-channel = { workspace = true }
db = { workspace = true }
tracing = { workspace = true }
