name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
        shell: bash
          
      - uses: Swatinem/rust-cache@v2
        
      - name: Unit tests
        run: |
          cargo test

      - name: Clippy lint
        run: |
          cargo clippy --no-deps -- -D warnings
