name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
        shell: bash
          
      - uses: Swatinem/rust-cache@v2
        
      - uses: actions-rs/cargo@v1
        name: Unit tests
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Clippy lint
        with:
          command: clippy --no-deps
